# coding: utf-8
# Copyright (c) 2025 inclusionAI.
"""
Task YAML Loader: Load Task instances from YAML configuration files.

This module provides utilities to:
1. Parse Task YAML files generated by SwarmComposerAgent
2. Instantiate agents of different types (builtin/skill/predefined)
3. Build swarm topology using swarm_builder
4. Create executable Task instances

Supported agent types:
- builtin: Inline configuration (uses agent_loader.load_agents_from_dict)
- skill: Build from Agentic Skill (skills/{skill_name}/skill.md)
- predefined: Reference to external agent instance
"""

import os
import re
from pathlib import Path
from typing import Dict, List, Any, Optional

import yaml

from aworld.agents.llm_agent import Agent
from aworld.config import AgentConfig, TaskConfig
from aworld.config.agent_loader import load_agents_from_dict
from aworld.core.agent.base import BaseAgent
from aworld.core.agent.swarm import Swarm
from aworld.core.agent.swarm_builder import build_swarm_from_dict
from aworld.core.context.amni.config import AmniContextConfig
from aworld.core.task import Task
from aworld.logs.util import logger
from aworld.utils.common import replace_env_variables


def _replace_variables_with_overrides(config: Any, overrides: Dict[str, Any]) -> Any:
    """
    Replace ${VAR_NAME} placeholders with values from overrides dict.
    
    This function replaces variables that were not found in environment variables
    or provides explicit overrides for specific variables.
    
    Args:
        config: Configuration to process (dict, list, or other value)
        overrides: Dict mapping variable names to replacement values
    
    Returns:
        Processed configuration with variables replaced
    
    Example:
        >>> config = {"model": "${LLM_MODEL}", "temp": 0.5}
        >>> overrides = {"LLM_MODEL": "gpt-4"}
        >>> _replace_variables_with_overrides(config, overrides)
        {"model": "gpt-4", "temp": 0.5}
    """
    if isinstance(config, dict):
        result = {}
        for key, value in config.items():
            result[key] = _replace_variables_with_overrides(value, overrides)
        return result
    
    elif isinstance(config, list):
        return [_replace_variables_with_overrides(item, overrides) for item in config]
    
    elif isinstance(config, str):
        # Match ${VAR_NAME} pattern
        pattern = r'\${([^}]+)}'
        matches = re.findall(pattern, config)
        
        for var_name in matches:
            if var_name in overrides:
                replacement_value = str(overrides[var_name])
                config = config.replace(f'${{{var_name}}}', replacement_value)
                logger.debug(f"  ✓ Replaced ${{{var_name}}} with override value")
        
        return config
    
    return config


def _load_yaml(path: str) -> Dict[str, Any]:
    """Load and parse YAML file with environment variable substitution."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"Task YAML file not found: {path}")
    
    with open(path, "r", encoding="utf-8") as f:
        try:
            data = yaml.safe_load(f) or {}
        except yaml.YAMLError as e:
            raise ValueError(f"Failed to parse YAML file: {e}")
    
    if not isinstance(data, dict):
        raise ValueError("Task YAML root must be a dictionary")
    
    # Replace ${ENV_VAR} placeholders
    data = replace_env_variables(data)
    
    return data


async def load_task_from_yaml(
    yaml_path: str,
    *,
    available_agents: Dict[str, BaseAgent] = None,
    skills_path: Optional[Path] = None,
    context_config: Optional[AmniContextConfig] = None,
    **task_overrides
) -> Task:
    """
    Load Task instance from YAML configuration.
    
    Args:
        yaml_path: Path to Task YAML file (generated by SwarmComposerAgent)
        available_agents: Dict of predefined agents for type='predefined' {agent_id: agent_instance}
        skills_path: Path to skills directory (required for type='skill' agents)
        context_config: Context configuration for the task
        **task_overrides: Override task-level configs (e.g., timeout, session_id, task_id)
    
    Returns:
        Task instance ready to execute via Runners.run_task()
    
    Raises:
        ValueError: If YAML is invalid or required resources are missing
        FileNotFoundError: If YAML file or skill files don't exist
    
    Example:
        >>> task = await load_task_from_yaml(
        ...     "task_plan.yaml",
        ...     available_agents={"search_agent": my_search_agent},
        ...     skills_path=Path("./skills")
        ... )
        >>> results = await Runners.run_task(task)
    """
    # 1. Parse YAML
    logger.info(f"📄 Loading Task YAML from: {yaml_path}")
    data = _load_yaml(yaml_path)
    
    # 2. Instantiate agents
    logger.info("🔧 Instantiating agents...")
    agents_dict = await _load_agents(
        data.get("agents", []),
        available_agents=available_agents,
        skills_path=skills_path,
        global_mcp_config=data.get("mcp_config")
    )
    logger.info(f"✅ Loaded {len(agents_dict)} agents: {list(agents_dict.keys())}")
    
    # 3. Build swarm
    logger.info("🕸️ Building swarm...")
    swarm = _build_swarm(data.get("swarm", {}), agents_dict)
    logger.info(f"✅ Built swarm: type={swarm.build_type}, agents={len(swarm.agents)}")
    
    # 4. Create Task
    task_meta = data.get("task", {})
    task_config_dict = data.get("task_config", {})
    task_config = TaskConfig(**task_config_dict) if task_config_dict else None
    # Portable absolute limits survive reloading/retrying a task plan. An
    # explicit caller override may tighten them, never erase an existing epoch.
    for key in ("timeout", "deadline_epoch_seconds"):
        if key in task_meta and key not in task_overrides:
            task_overrides[key] = task_meta[key]
    if task_meta.get("deadline_epoch_seconds") is not None:
        existing = task_meta["deadline_epoch_seconds"]
        supplied = task_overrides.get("deadline_epoch_seconds")
        Task(deadline_epoch_seconds=existing)
        if supplied is not None:
            Task(deadline_epoch_seconds=supplied)
        task_overrides["deadline_epoch_seconds"] = min(existing, supplied) if supplied is not None else existing
    
    task = Task(
        input=task_overrides.get("input") or task_meta.get("query"),
        session_id=task_overrides.get("session_id") or task_meta.get("session_id"),
        id=task_overrides.get("task_id") or task_meta.get("task_id"),
        swarm=swarm,
        tool_names=data.get("tools", []),
        context_config=context_config,
        conf=task_config,
        **{k: v for k, v in task_overrides.items() if k not in ["input", "session_id", "task_id"]}
    )
    
    logger.info(f"✅ Task created: id={task.id}, session={task.session_id}")
    return task


async def _load_agents(
    agents_config: List[Dict[str, Any]],
    available_agents: Optional[Dict[str, BaseAgent]],
    skills_path: Optional[Path],
    global_mcp_config: Optional[Dict[str, Any]]
) -> Dict[str, BaseAgent]:
    """
    Load and instantiate agents based on type.
    
    Args:
        agents_config: List of agent definitions from YAML
        available_agents: Dict of predefined agents
        skills_path: Path to skills directory
        global_mcp_config: Global MCP configuration
    
    Returns:
        Dict mapping agent_id to Agent instance
    
    Raises:
        ValueError: If agent is missing or configuration is invalid
    """
    from aworld.utils.skill_loader import collect_skill_docs
    
    agents_dict = {}
    available_agents = available_agents or {}
    
    for agent_def in agents_config:
        if not isinstance(agent_def, dict):
            raise ValueError(f"Agent definition must be a dictionary, got: {type(agent_def)}")
        
        agent_id = agent_def.get("id")
        if not agent_id:
            raise ValueError("Each agent must have an 'id' field")
        
        agent_type = agent_def.get("type", "builtin")
        
        try:
            if agent_type == "builtin":
                agent = await _load_builtin_agent(agent_id, agent_def, global_mcp_config)
            
            elif agent_type == "skill":
                agent = await _load_skill_agent(agent_id, agent_def, skills_path, global_mcp_config)
            
            elif agent_type == "predefined":
                agent = _load_predefined_agent(agent_id, agent_def, available_agents)
            
            else:
                raise ValueError(f"Unknown agent type: {agent_type}")
            
            agents_dict[agent_id] = agent
            logger.debug(f"  ✓ Loaded agent '{agent_id}' (type={agent_type})")
        
        except Exception as e:
            logger.error(f"  ✗ Failed to load agent '{agent_id}': {e}")
            raise
    
    return agents_dict


async def _load_builtin_agent(
    agent_id: str,
    agent_def: Dict[str, Any],
    global_mcp_config: Optional[Dict[str, Any]]
) -> BaseAgent:
    """
    Load builtin agent using agent_loader.load_agents_from_dict.
    
    This reuses existing agent loading logic for consistency.
    """
    # Transform to agent_loader format: {agent_id: {...config...}}
    builtin_dict = {agent_id: {
        "system_prompt": agent_def.get("system_prompt"),
        "desc": agent_def.get("desc", ""),
        "config": agent_def.get("config", {}),
        "mcp_servers": agent_def.get("mcp_servers", []),
        "mcp_config": _merge_mcp_configs(
            global_mcp_config, 
            agent_def.get("mcp_config")
        )
    }}
    
    # Remove None values
    builtin_dict[agent_id] = {k: v for k, v in builtin_dict[agent_id].items() if v is not None}
    
    loaded = load_agents_from_dict(builtin_dict)
    return loaded[agent_id]


async def _load_skill_agent(
    agent_id: str,
    agent_def: Dict[str, Any],
    skills_path: Optional[Path],
    global_mcp_config: Optional[Dict[str, Any]]
) -> BaseAgent:
    """
    Load agent from Agentic Skill (skill.md with type: agent).
    
    Raises:
        ValueError: If skill not found, not Agentic Skill, or skills_path missing
    """
    from aworld.skills.compat_provider import build_compat_registry
    
    skill_name = agent_def.get("skill_name")
    if not skill_name:
        raise ValueError(f"missing agent {agent_id}: 'skill_name' field is required for agent type 'skill'")
    
    if not skills_path:
        raise ValueError(f"missing agent {agent_id}: skills_path required for agent type 'skill'")
    
    # Check if skills_path exists
    if not skills_path.exists():
        raise ValueError(f"missing agent {agent_id}: skills_path does not exist: {skills_path}")
    
    # Discover descriptors first, then lazily load content for the selected skill only.
    try:
        registry = build_compat_registry(skills_path)
    except Exception as e:
        raise ValueError(f"missing agent {agent_id}: failed to load skills from {skills_path}: {e}")

    descriptors = {
        descriptor.skill_name: descriptor
        for descriptor in registry.list_descriptors()
    }

    if skill_name not in descriptors:
        available_skills = ', '.join(descriptors.keys()) if descriptors else 'none'
        raise ValueError(
            f"missing agent {agent_id}: Skill '{skill_name}' not found in {skills_path}. "
            f"Available skills: {available_skills}"
        )

    descriptor = descriptors[skill_name]

    # Verify it's an Agentic Skill
    skill_type = str(descriptor.metadata.get("type", ""))
    if skill_type != "agent":
        raise ValueError(
            f"missing agent {agent_id}: Skill '{skill_name}' is not an Agentic Skill "
            f"(type='{skill_type}', expected type='agent')"
        )

    try:
        content = registry.load_content(descriptor.skill_id)
    except Exception as e:
        raise ValueError(
            f"missing agent {agent_id}: failed to load skill content for '{skill_name}' "
            f"from {skills_path}: {e}"
        )

    runtime_skill_config = registry.build_skill_config(
        descriptor.skill_id,
        active_override=True,
    )
    
    # Build Agent from skill (consistent with skill_service logic)
    agent_config_dict = agent_def.get("config", {})
    
    # If no llm_config provided, use environment variables
    if "llm_config" not in agent_config_dict:
        agent_config_dict["llm_config"] = {
            "llm_model_name": os.getenv("LLM_MODEL_NAME"),
            "llm_provider": os.getenv("LLM_PROVIDER"),
            "llm_api_key": os.getenv("LLM_API_KEY"),
            "llm_base_url": os.getenv("LLM_BASE_URL"),
        }
    
    agent_config = AgentConfig(**agent_config_dict) if agent_config_dict else AgentConfig()
    
    agent = Agent(
        name=agent_id,
        desc=descriptor.description,
        conf=agent_config,
        system_prompt=content.usage,
        mcp_servers=list(dict(content.tool_list).keys()),
        mcp_config=_merge_mcp_configs(
            global_mcp_config, 
            agent_def.get("mcp_config")
        )
    )

    # Preserve framework-loaded skill metadata for downstream runtime features
    # such as remote sandbox execution-asset staging without re-enabling the
    # legacy skill tool path on these agentic skills.
    merged_skill_configs = dict(agent.conf.skill_configs or {})
    merged_skill_configs[skill_name] = runtime_skill_config

    agent.conf.skill_configs = merged_skill_configs
    agent.skill_configs = merged_skill_configs
    if agent.sandbox is not None:
        agent.sandbox.skill_configs = merged_skill_configs
    
    return agent


def _load_predefined_agent(
    agent_id: str,
    agent_def: Dict[str, Any],
    available_agents: Dict[str, BaseAgent]
) -> BaseAgent:
    """
    Load predefined agent from available_agents dict.
    
    Raises:
        ValueError: If agent not found in available_agents
    """
    agent_name = agent_def.get("predefined_agent")
    agent = available_agents.get(agent_id) or available_agents.get(agent_name)
    if not agent:
        available = ', '.join(available_agents.keys()) if available_agents else 'none'
        raise ValueError(
            f"missing agent {agent_id}/{agent_name}: agent not found in available_agents. "
            f"Available predefined agents: {available}"
        )
    
    return agent


def _build_swarm(swarm_config: Dict[str, Any], agents_dict: Dict[str, BaseAgent]) -> Swarm:
    """
    Build Swarm from config using swarm_builder.
    
    Args:
        swarm_config: Swarm configuration from YAML
        agents_dict: Dict of instantiated agents
    
    Returns:
        Swarm instance
    
    Raises:
        ValueError: If swarm configuration is invalid
    """
    if not swarm_config:
        raise ValueError("Task YAML must contain 'swarm' section")
    
    # Wrap in format expected by swarm_builder
    config = {"swarm": swarm_config}
    
    try:
        swarm = build_swarm_from_dict(config, agents_dict)
        return swarm
    except Exception as e:
        raise ValueError(f"Failed to build swarm: {e}")


def _merge_mcp_configs(
    global_config: Optional[Dict[str, Any]], 
    agent_config: Optional[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Merge global and agent-level MCP configs.
    
    Agent-level config takes precedence over global config.
    """
    if not global_config:
        return agent_config or {}
    if not agent_config:
        return global_config
    
    # Deep merge mcpServers
    merged = {"mcpServers": {}}
    merged["mcpServers"].update(global_config.get("mcpServers", {}))
    merged["mcpServers"].update(agent_config.get("mcpServers", {}))
    
    return merged


async def load_swarm_from_yaml_dict(
    yaml_dict: Dict[str, Any],
    *,
    available_agents: Dict[str, BaseAgent] = None,
    skills_path: Optional[Path] = None,
    global_mcp_config: Dict[str, Any] = None,
    **swarm_overrides
) -> Swarm:
    """
    Load Swarm from parsed YAML dictionary (without Task).
    
    This function extracts only the agents and swarm sections from a complete
    Task YAML and returns a Swarm instance.
    
    Args:
        yaml_dict: Parsed YAML dict containing 'agents' and 'swarm' sections
        available_agents: Dict of predefined agents for type='predefined'
        skills_path: Path to skills directory (required for type='skill' agents)
        global_mcp_config: Global MCP configuration (from yaml_dict or override)
        **swarm_overrides: Override swarm-level configs and variable substitutions.
            Swarm attributes (e.g., max_steps, event_driven) are applied to the Swarm instance.
            Non-swarm-attribute keys are treated as variable substitutions for ${KEY} placeholders.
    
    Returns:
        Swarm instance ready to be used in Task creation
    
    Raises:
        ValueError: If YAML is invalid or required resources are missing
    
    Example:
        >>> # Example 1: Basic usage
        >>> yaml_dict = {
        ...     "agents": [...],
        ...     "swarm": {...},
        ...     "mcp_config": {...}
        ... }
        >>> swarm = await load_swarm_from_yaml_dict(
        ...     yaml_dict,
        ...     skills_path=Path("./skills")
        ... )
        >>> 
        >>> # Example 2: With variable overrides
        >>> swarm = await load_swarm_from_yaml_dict(
        ...     yaml_dict,
        ...     max_steps=20  # Swarm attribute override
        ... )
    """
    logger.info("🕸️ Loading Swarm from YAML dictionary...")
    
    # 0. Variable substitution
    # First, replace environment variables
    yaml_dict = replace_env_variables(yaml_dict)
    
    # 1. Extract global_mcp_config from yaml_dict if not provided
    if global_mcp_config is None:
        global_mcp_config = yaml_dict.get("mcp_config")
    
    # 2. Instantiate agents
    logger.info("🔧 Instantiating agents...")
    agents_dict = await _load_agents(
        yaml_dict.get("agents", []),
        available_agents=available_agents,
        skills_path=skills_path,
        global_mcp_config=global_mcp_config
    )
    logger.info(f"✅ Loaded {len(agents_dict)} agents: {list(agents_dict.keys())}")
    
    # 3. Build swarm
    logger.info("🕸️ Building swarm...")
    swarm = _build_swarm(yaml_dict.get("swarm", {}), agents_dict)
    
    # 4. Apply swarm attribute overrides (if the key is a Swarm attribute)
    for key, value in swarm_overrides.items():
        if hasattr(swarm, key):
            setattr(swarm, key, value)
            logger.debug(f"  ✓ Applied swarm attribute override: {key}={value}")
    
    logger.info(f"✅ Swarm loaded: type={swarm.build_type}, agents={len(swarm.agents)}")
    return swarm


async def load_swarm_from_yaml(
    yaml_path: str,
    *,
    available_agents: Dict[str, BaseAgent] = None,
    skills_path: Optional[Path] = None,
    **swarm_overrides
) -> Swarm:
    """
    Load Swarm from standalone swarm.yaml file.
    
    This supports loading from files that contain only agents + swarm sections
    (without task section), enabling users to define reusable swarm configurations.
    
    Args:
        yaml_path: Path to swarm YAML file
        available_agents: Dict of predefined agents
        skills_path: Path to skills directory
        **swarm_overrides: Override swarm-level configs
    
    Returns:
        Swarm instance
    
    Raises:
        ValueError: If YAML is invalid or required resources are missing
        FileNotFoundError: If YAML file doesn't exist
    
    Example:
        >>> swarm = await load_swarm_from_yaml(
        ...     "swarms/stock_analysis_team.yaml",
        ...     skills_path=Path("./skills")
        ... )
    """
    logger.info(f"📄 Loading Swarm from YAML file: {yaml_path}")
    
    # 1. Load YAML
    yaml_dict = _load_yaml(yaml_path)
    
    # 2. Call load_swarm_from_yaml_dict
    swarm = await load_swarm_from_yaml_dict(
        yaml_dict,
        available_agents=available_agents,
        skills_path=skills_path,
        **swarm_overrides
    )
    
    return swarm
